import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import xgboost as xgb
import shap
from sklearn.preprocessing import MinMaxScaler
from mpl_toolkits.axes_grid1 import make_axes_locatable

# 1. Global Styling - Strict normalization
plt.rcParams['font.family'] = 'sans-serif'
plt.rcParams['font.sans-serif'] = 'Arial'
plt.rcParams['axes.unicode_minus'] = False
plt.rcParams['font.size'] = 7 

def create_multi_target_shap_plots():
    print("\n--- Initializing Multi-Target SHAP Visualization ---")

    dataset_path = r"C:\Users\ateya\OneDrive - Indian Institute of Science\Optimization.xlsx"
    
    if not os.path.exists(dataset_path):
        print(f"Error: Dataset not found at {dataset_path}.")
        return

    dataset = pd.read_excel(dataset_path, sheet_name='new data')

    feature_columns = [
        'Fe', 'C', 'Si', 'Mn', 'P', 'S', 'Ni', 'Cr', 'Mo', 'Cu', 'Al', 'N', 'V', 'Nb', 'Ta', 'W', 'Ti', 'B',
        'Sn', 'Zr', 'Co', 'O', 'Temperature'
    ]
    
    targets = {
        '0.2% Proof Stress': {
            'colsample_bytree': 1.0, 'learning_rate': 0.07, 'max_depth': 7, 
            'n_estimators': 350, 'subsample': 0.7, 'random_state': 42
        },
        'Tensile Strength': {
            'colsample_bytree': 0.6, 'learning_rate': 0.3, 'max_depth': 5, 
            'n_estimators': 1000, 'subsample': 0.9, 'random_state': 42
        },
        'Elongation %': {
            'colsample_bytree': 0.7, 'learning_rate': 0.1, 'max_depth': 5, 
            'n_estimators': 450, 'subsample': 0.6, 'random_state': 42
        }
    }

    dataset[feature_columns] = dataset[feature_columns].fillna(0)
    scaler = MinMaxScaler()
    custom_cmap = plt.get_cmap("coolwarm")

    for target_name, params in targets.items():
        print(f"Processing: {target_name}")
        
        current_df = dataset.dropna(subset=[target_name])
        X_scaled = scaler.fit_transform(current_df[feature_columns].values)
        y = current_df[target_name].values

        model = xgb.XGBRegressor(**params)
        model.fit(X_scaled, y)

        explainer = shap.TreeExplainer(model)
        shap_values = explainer.shap_values(X_scaled)

        # --- VISUALIZATION BLOCK ---
        # 7 width by 10.5 height sets a clean canvas footprint
        fig, ax = plt.subplots(figsize=(7, 10.5), dpi=300)
        
        # Lock the physical plot box to a strict 1.5:1 portrait aspect ratio
        # (Use 1 / 1.5 if you prefer a wider landscape layout instead)
        ax.set_box_aspect(1/1.25)
        
        # 1. GENERATE NATIVE SHAP PLOT
        # Removed `s` keyword argument to prevent the summary_legacy TypeError
        shap.summary_plot(
            shap_values, 
            X_scaled, 
            feature_names=feature_columns, 
            plot_type="dot", 
            show=False,
            max_display=20,
            color_bar=False 
        )

        
        plt.box(True)
        for spine in ax.spines.values():
            spine.set_visible(True)
            spine.set_linewidth(0.8)

        
        # Directly update the PathCollection elements generated by the summary plot
        for fc in ax.get_children():
            if isinstance(fc, mpl.collections.PathCollection):
                fc.set_cmap(custom_cmap)
                # <--- CRITICAL OVERRIDE: Shrink dot sizes post-rendering natively
                fc.set_sizes([3])  

        
        ax.set_xlabel("SHAP Value (Impact on Model Output)", fontsize=7, labelpad=0)
        ax.tick_params(axis='x', labelsize=7)
        
        ax.tick_params(axis='y', labelsize=7, pad=-17)
        plt.setp(ax.get_yticklabels(), ha='right') 

        ax.set_ylabel("Features", fontsize=7, labelpad=-5)

        # 5. COLORBAR INTERFACE CONFIGURATION
        divider = make_axes_locatable(ax)
        cax = divider.append_axes("right", size="2.5%", pad=0.03)
        
        norm = mpl.colors.Normalize(vmin=0, vmax=1)
        cb = mpl.colorbar.ColorbarBase(cax, cmap=custom_cmap, norm=norm, orientation='vertical')
        
        cb.set_ticks([0, 1])
        cb.set_ticklabels(['Low', 'High'], fontsize=7)
        cb.set_label('Feature Value', size=7, labelpad=1)
        
        cb.outline.set_visible(True)
        cb.outline.set_linewidth(0.8)

        
        ax.axvline(x=0, color='black', linestyle='-', linewidth=0.6, alpha=0.4)
        ax.grid(False)

        
        plt.subplots_adjust(left=0.22, right=0.86, top=0.92, bottom=0.10)

        plt.show()

if __name__ == "__main__":
    create_multi_target_shap_plots()